image: php:8.4

stages:
  - build
  - test

build:php-libs:
  stage: build
  image: composer:2.8
  cache:
    key:
      files:
        - composer.lock
    policy: pull-push
    paths:
      - vendor
    when: always
  artifacts:
    expire_in: 7 days
    paths:
      - vendor
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
  script: composer install --no-interaction --optimize-autoloader

test:pest:
  stage: test
  image: serversideup/php:8.4-cli-alpine
  variables:
    SHOW_WELCOME_MESSAGE: "false"
  dependencies:
    - build:php-libs
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - cp .env.example .env
    - php artisan key:generate
  script:
    - php artisan config:clear --no-ansi
    - php artisan test

test:style:
  stage: test
  image: serversideup/php:8.4-cli-alpine
  variables:
    SHOW_WELCOME_MESSAGE: "false"
  dependencies:
    - build:php-libs
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - apk add --no-cache git zip unzip
  script:
    - ./vendor/bin/pint --test

test:phpstan:
  stage: test
  image: serversideup/php:8.4-cli-alpine
  variables:
    SHOW_WELCOME_MESSAGE: "false"
  dependencies:
    - build:php-libs
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "development"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"
    - if: $CI_COMMIT_BRANCH == "main"
  before_script:
    - cp .env.example .env
  script:
    - ./vendor/bin/phpstan analyse
